version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: npm run start
    depends_on:
      - mongo
    networks:
      - cinema-api

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - 'mongodb:/data/db'
    networks:
      - cinema-api

volumes:
  mongodb:

networks:
  cinema-api:
    driver: bridge